### Decomposição Cholesky

Se a matriz $A$ é simétrica e definida positiva, podemos decompô-la unicamente no produto $GG^{t}$, onde $G$ é uma matriz triangular inferior com elementos positivos na diagonal. Uma matriz simetrica $A$ é definida positiva se, e somente se, seus autovalores sao reais e positivos.

Seja
$A=
  \left[ {\begin{array}{cc}
   a_{11} & a_{12} & \dots & a_{1n} \\
   a_{21} & a_{22} & \dots & a_{2n} \\
   \vdots & \vdots & \ddots & \vdots \\
   a_{n1} & a_{n2} & \dots & a_{nn} \\
  \end{array} } \right] =
 $ 
 $  
   \left[ {\begin{array}{cc}
   g_{11} & 0      & \dots  & 0 \\
   g_{21} & g_{22} & \dots  & 0 \\
   \vdots & \vdots & \ddots & \vdots \\
   g_{n1} & g_{n2} & \dots  & g_{nn} \\
  \end{array} } \right] *
  $
  $
  \left[ {\begin{array}{cc}
   g_{11} & g_{21} & \dots  & g_{n1} \\
   0      & g_{22} & \dots  & g_{n2} \\
   \vdots & \vdots & \ddots & \vdots \\
   0      & 0      & \dots  & g_{nn} \\
  \end{array} } \right]$

### Calculando as diagonais principais:

$a_{11} = g_{11}^2 $<br>
$a_{22} = g_{21}^2 + g_{22}^2$<br>
$\vdots $<br>
$a_{nn} = g_{n1}^2 + g_{n2}^2 + \dots + g_{nn}^2$

Assim,

$ g_{11} = \sqrt{a_{11}} $ <br>
$g_{22} = \sqrt{a_{22} - g_{21}^2}$ <br>
$\vdots$ <br>
$g_{nn} = \sqrt{a_{nn} - g_{n1}^2 - g_{n2}^2 - \dots - g_{nn-1}^2}$

Regra geral,

$ g_{11} = \sqrt{a_{11}} $  <br>
$g_{ii} = \sqrt{a_{ii} - \sum_{k = 1}^{i-1}g_{ik}^2},  i = 2,3 \dots n $

### Fórmula Geral

### $g_{i1} = \frac{a_{i1}}{g_{11}} $, $ \forall i \in {1,2, \dots n}$<br>
### $g_{ij} = \frac{(a_{ij} - \sum_{k=1}^{j-1} g_{ik}*g_{jk})}{g_{jj}}$

### Determinante

$ A = G^{t}G $ <br>
$ det(A) = det(G^{t}) * det(G) $<br> 
$det(A) = (a_{11} * a_{22} * \dots *a_{nn})^2
$


In [7]:
import numpy as np

In [8]:
def is_simetric(matrix):
    n = len(matrix)
    for i in range(n):
        for j in range(i,n):
            if i != j :
                if matrix[i][j] != matrix[j][i]:
                    return False
    return True

def is_defined_positive(matrix):
    eigvalues = np.linalg.eigvals(matrix)
    for i in eigvalues:
        if(not np.isreal(i)):
            return False
    return min(eigvalues)>0

In [64]:
def Cholesky(matrix):
    if not is_simetric(matrix):
        print(is_defined_positive(matrix))
        print("Não é simética")
        return None,None
    
    else:
        n = len(matrix)
        g = np.zeros((n,n))
        for i in range(0,n):
            acc = 0
            for k in range(0,i):
                acc += (g[i][k]**2)
            g[i][i] = (matrix[i][i] - acc)**(1/2)        

            for j in range(i+1,n):
                acc2 = 0
                for k in range(0,j-1):
                    acc2 += (g[i][k]*g[j][k])
                g[j][i] = (matrix[j][i] - acc2)/g[i][i]

        return g,g.T,(g.diagonal().prod())**2 # matriz e o determinante

    
def solve(A,b):
    n = len(b)
    y = np.zeros(n)
    x = np.zeros(n)
    L, U, det = Cholesky(A)
    
    
    y[0] = b[0]/L[0][0]
    for i in range(1, n):
        suma = 0.0
        for j in range(i):
            suma += L[i][j] * y[j]
        y[i] = (b[i] - suma)/L[i][i]

    x[n-1] = y[n-1]/U[n-1][n-1]
    for i in range(n-1, -1, -1):
        suma = y[i]
        for j in range(i+1, n):
            suma = suma - U[i][j] * x[j]
        x[i] = suma/U[i][i]
    return x

def verify(A,x,b):
    r = np.dot(A,x)
    return r == b

In [61]:
matrix = np.array([[4.0,2.0,-4.0],[2.0,10.0,4.0],[-4.0,4.0,9.0]])
b = np.array([3,3,5])
resultado = solve(matrix,b)

In [63]:
verify(matrix,resultado,b)

array([ True,  True,  True])

In [45]:
a = np.array([[1,2],[1,2]])
b = np.array([[1,2],[1,2]])
np.dot(a,b)

array([[3, 6],
       [3, 6]])

In [49]:
m2 = np.array([[4,-1,1],[-1,4.25,2.75],[1,2.75,3.5]])

In [51]:
R,RT,determinante = Cholesky(m2)
print(R)

[[ 2.   0.   0. ]
 [-0.5  2.   0. ]
 [ 0.5  1.5  1. ]]


In [52]:
np.dot(R, R.T)

array([[ 4.  , -1.  ,  1.  ],
       [-1.  ,  4.25,  2.75],
       [ 1.  ,  2.75,  3.5 ]])

In [53]:
np.linalg.cholesky(matrix)

array([[ 2.,  0.,  0.],
       [ 1.,  3.,  0.],
       [-2.,  2.,  1.]])

In [54]:
np.linalg.cholesky(m2)

array([[ 2. ,  0. ,  0. ],
       [-0.5,  2. ,  0. ],
       [ 0.5,  1.5,  1. ]])

In [55]:
a = np.array([[4,-1,1],[-1,4.25,2.75],[1,2.75,3.5]])

In [56]:
a

array([[ 4.  , -1.  ,  1.  ],
       [-1.  ,  4.25,  2.75],
       [ 1.  ,  2.75,  3.5 ]])

In [57]:
m3 = np.array([[4,-12,8],[-12,45,-42],[8,-42,68]])

In [59]:
Cholesky(m3)[0]

array([[ 2.,  0.,  0.],
       [-6.,  3.,  0.],
       [ 4., -6.,  4.]])